"use client";

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { RecoilRoot } from "recoil";
import Sidebar from "@/app/components/Sidebar/Sidebar";
import Header from "@/app/components/Header/Header";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <RecoilRoot>
          <div
            className={
              "fixed z-10 top-[-56px] left-0 right-0 w-[255px] bg-gray-400"
            }
          >
            <Header />
          </div>
          <div className={"fixed top-0 left-0 bottom-0 w-[255px] bg-gray-400"}>
            <Sidebar />
          </div>
          {children}
        </RecoilRoot>
      </body>
    </html>
  );
}
